FROM golang:1.22-alpine
WORKDIR /app
RUN apk add --no-cache gcc musl-dev
RUN go install github.com/air-verse/air@latest
ENV TZ=America/Toronto
ENV CGO_ENABLED=1
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
