version: "2"

linters:
  default: none
  enable:
    - errcheck        # unchecked errors
    - gosimple        # simplification suggestions
    - govet           # go vet checks
    - ineffassign     # unused assignments
    - staticcheck     # comprehensive static analysis
    - unused          # unused code
    - goimports       # import order + formatting
    - misspell        # common English spelling mistakes
    - gocritic        # opinionated checks (many useful patterns)
    - noctx           # HTTP requests without context
    - bodyclose       # unclosed HTTP response bodies
    - exhaustive      # missing switch cases on enums

linters-settings:
  goimports:
    local-prefixes: clearoutspaces
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # Test files: allow unused params and error ignores in helpers.
    - path: "_test\\.go"
      linters:
        - errcheck
        - unused
  max-same-issues: 0
